<template>
  <div>
    <v-card>
      <v-card-title>
        Codes
        <v-btn :loading="loading" icon>
          <v-icon @click="getCodes">mdi-reload</v-icon>
        </v-btn>
        <v-spacer></v-spacer>
        <v-col cols="4" sm="2">
          <v-text-field
              v-model="numberOfCodesToGenerate"
              hint="Number of codes to generate"
              persistent-hint
              type="number"
              :rules="[rules.positiveNumber]"
          ></v-text-field>
        </v-col>

        <v-btn fab color="green" small :disabled="invalidGeneration" @click="generateCodes">
          <v-icon>mdi-plus</v-icon>
        </v-btn>
      </v-card-title>
      <v-card-subtitle>
        <v-row>
          <v-col>
            Video Title: {{ video.title }}
            <br>
            <v-radio-group v-model="accessedBy" row @change="options.page = 1; getCodes();">
              <template v-slot:label>
                Access given by:
              </template>
              <v-radio label="Manual" value="manual"></v-radio>
              <v-radio label="Code" value="code"></v-radio>
              <v-radio label="Both" value="both"></v-radio>
            </v-radio-group>
          </v-col>
          <v-col cols="6" md="4">
            <v-text-field
                v-model="search"
                label="Search by code, generated by, or used by"
                prepend-icon="mdi-magnify"
                @input="getCodes"
            ></v-text-field>
          </v-col>
        </v-row>
      </v-card-subtitle>

      <v-data-table
          :headers="headers"
          :items="codes"
          class="elevation-1"
          :loading="loading"
          :options.sync="options"
          :server-items-length="totalCodes"
          :footer-props="{
        'items-per-page-options': [10, 15, 20,-1],
        'show-current-page': true,
        'show-first-last-page': true,
      }"
          :items-per-page="10"
          must-sort
      >

        <template v-slot:item.value="{item}">
          <div v-if="item.manual">Manual Access</div>
          <div v-else>{{ item.value }}</div>
        </template>

        <template v-slot:item.created_at="{item}">
          {{ item.CreatedAt | momentFormatDate }}
        </template>

        <template v-slot:item.created_by_user.full_name="{item}">
          {{ item.createdByUser.fullName }}
        </template>

        <template v-slot:item.used_by_user_id="{item}">
          <v-icon color="green" dark v-if="item.usedByUserID !== 0">mdi-check-bold</v-icon>
          <v-icon color="red" dark v-else>mdi-close-circle</v-icon>
        </template>

        <template v-slot:item.used_by_user.full_name="{item}">
          {{ item.usedByUser.fullName }}
        </template>

        <template v-slot:item.delete="{item}">
          <ConfirmationDialog v-if="item.usedByUserID !== 0"
              buttonText="Remove"
              :mainText="'Remove Access from (' + item.usedByUser.fullName + ') ?'"
              message="The selected user won't be able to access this video anymore - Unless you accessed him again"
              video-code
              :deleted-item-name="item.usedByUser.fullName"
              @confirm="removeAccess($event, item)"
          ></ConfirmationDialog>
        </template>

      </v-data-table>
    </v-card>
  </div>
</template>

<script>
import api from "@/gateways/api";
import moment from "moment";
import ConfirmationDialog from "@/components/utils/ConfirmationDialog";

export default {
  name: "VideoCodes",
  components: {ConfirmationDialog},
  props: ['video'],
  data() {
    return {
      numberOfCodesToGenerate: 1,
      rules: {
        positiveNumber: value => (value > 0 && value <= 250) || 'Value must be between 0 and 250',
      },
      headers: [
        {text: 'Code', value: 'value', sortable: false},
        {text: 'Generated By', value: 'created_by_user.full_name'},
        {text: 'Generated At', value: 'created_at'},
        {text: 'Used', value: 'used_by_user_id', width: "10%"},
        {text: 'Used By', value: 'used_by_user.full_name', width: "20%"},
        {text: 'Delete', value: 'delete', sortable: false}
      ],
      codes: [],
      options: {
        sortBy: ['used_by_user.full_name'],
        sortDesc: ['true'],
      },
      loading: false,
      totalCodes: 0,
      search: '',
      accessedBy: 'both',
    }
  },
  computed: {
    invalidGeneration() {
      return this.numberOfCodesToGenerate <= 0 || this.numberOfCodesToGenerate > 250
    }
  },
  methods: {
    generateCodes() {
      let formData = new FormData()
      formData.append("videoID", this.video.ID)
      formData.append("numberOfCodes", this.numberOfCodesToGenerate)
      api({
        method: "POST",
        url: "/admin/videos/codes",
        data: formData
      })
    },
    getCodes() {
      this.loading = true
      const {sortBy, sortDesc, page, itemsPerPage} = this.options
      api({
        method: "GET",
        url: "/admin/videos/codes",
        params: {
          videoID: this.video.ID,
          page: page,
          itemsPerPage: itemsPerPage,
          sortBy: sortBy,
          sortDesc: sortDesc,
          search: this.search,
          accessedBy: this.accessedBy
        }
      }).then(response => {
        this.codes = response.data.codes
        this.totalCodes = response.data.total
      }).finally(() => {
        this.loading = false
      })
    },
    removeAccess($event, item) {
      this.loading = true
      let formData = new FormData()
      formData.append("codeValue", item.value)
      formData.append("typedValue", $event.typedValue)
      api({
        method: "DELETE",
        url: "/admin/videos/codes/code",
        data: formData
      }).then(() => {
        this.getCodes()
      }).finally(() => {
        this.loading = false
      })
    }
  },
  watch: {
    options: {
      handler() {
        this.getCodes();
      },
      deep: true,
    },
  },
  mounted() {
    this.getCodes()
  },
  filters: {
    momentFormatDate: function (date) {
      return moment(date).format('Do MMM YYYY, h a');
    },
  },
}
</script>

<style scoped>

</style>